A-785: Update reference to latest bazel-deps

diff --git a/deps b/deps
--- a/deps
+++ b/deps
@@ -3,9 +3,9 @@
 ROOT=`pwd`
 
 BAZEL_DEPS_REPO="https://github.com/input-output-hk/bazel-deps.git"
-BAZEL_DEPS_COMMIT="c9f440d823c987ce6ad86faf10fd53ecf6d9bbc7"
+BAZEL_DEPS_TAG="latest"
 
-IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_COMMIT"
+IDENTIFIER="$BAZEL_DEPS_REPO|$BAZEL_DEPS_TAG"
 
 BAZEL_DEPS="/tmp/$(echo "$IDENTIFIER" | sha256sum | awk '{ print $1 }')/.bazel-deps/"
 
@@ -25,7 +25,7 @@ if [ -e $BAZEL_DEPS ]; then
 else
     git clone "$BAZEL_DEPS_REPO" "$BAZEL_DEPS" || fail "Repo could not be found"
     cd "$BAZEL_DEPS"
-    git checkout "$BAZEL_DEPS_COMMIT" || fail "Commit could not be found"
+    git checkout "$BAZEL_DEPS_TAG" || fail "Tag could not be found"
 fi
 
 bazel run //:parse -- generate --repo-root $ROOT --deps "$ROOT/dependencies.yaml" --external 3rdparty 
